<a href="https://colab.research.google.com/github/ezhilarasik/ezhilprojects/blob/master/first.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
a=5
b=6
print(a+b)

11


Regression Model

In [7]:
import pandas as pd
import numpy as np

In [5]:
from google.colab import files
uploaded = files.upload()

Saving dataset.csv to dataset.csv


In [8]:
dataset=pd.read_csv("dataset.csv")
print(dataset)

    Age  Salary  Status
0    18   45000       0
1    20   50000       1
2    25   60000       0
3    28   34000       1
4    90   12000       1
5    60   45000       1
6    21   45000       1
7    23   50000       1
8    34   60000       0
9    21   34000       1
10   54   12000       0
11   34   45000       0
12   19   45000       0
13   21   50000       1
14   24   70000       1
15   27   34000       1
16   93   12000       1
17   61   45000       0
18   22   45000       0
19   24   50000       0
20   35   60000       0
21   23   34000       0
22   55   12000       0
23   40   45000       0


In [9]:
print(dataset.shape)
print(dataset.head(10))

(24, 3)
   Age  Salary  Status
0   18   45000       0
1   20   50000       1
2   25   60000       0
3   28   34000       1
4   90   12000       1
5   60   45000       1
6   21   45000       1
7   23   50000       1
8   34   60000       0
9   21   34000       1


In [10]:
X= dataset.iloc[:, :-1].values
X


array([[   18, 45000],
       [   20, 50000],
       [   25, 60000],
       [   28, 34000],
       [   90, 12000],
       [   60, 45000],
       [   21, 45000],
       [   23, 50000],
       [   34, 60000],
       [   21, 34000],
       [   54, 12000],
       [   34, 45000],
       [   19, 45000],
       [   21, 50000],
       [   24, 70000],
       [   27, 34000],
       [   93, 12000],
       [   61, 45000],
       [   22, 45000],
       [   24, 50000],
       [   35, 60000],
       [   23, 34000],
       [   55, 12000],
       [   40, 45000]])

In [11]:
Y=dataset.iloc[:, -1].values
Y

array([0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0])

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test =  train_test_split(X,Y,test_size=0.25,random_state=0)

In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train = sc.fit_transform(X_train)
X_test =  sc.fit_transform(X_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
model =  LogisticRegression()
model.fit(X_train,Y_train)

In [19]:
y_pred =model.predict(X_test)
print(y_pred.reshape(len(y_pred),1))

[[0]
 [1]
 [1]
 [0]
 [0]
 [0]]


In [21]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(Y_test,y_pred)
print(cm)
print(accuracy_score(Y_test,y_pred)*100)

[[2 2]
 [2 0]]
33.33333333333333
