<a href="https://colab.research.google.com/github/ezhilarasik/ezhilprojects/blob/master/kneighbour.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [16]:
from google.colab import files
uploaded= files.upload()

Saving salary.csv to salary (2).csv


In [17]:
dataset = pd.read_csv("salary (2).csv")

In [18]:
print(dataset)
print(dataset.shape)

    Age  education  Capital gain  hours salary
0    10         10             0     40   >=50
1    11          9             0     35   >=50
2    23          6             0     40   >=50
3    34         18             0     40    <50
4    45         17             0     50    <50
5     5          2             0     40   >=50
6     6          2             0     35    <50
7    67          5             0     40   >=50
8    32          4             1     40   >=50
9    41          4             1     23    <50
10   20          4             1     20   >=50
11   14         11             0     40   >=50
12   13         12             0     35   >=50
13   16         13             0     40   >=50
14   17         14             0     40    <50
15   19         15             0     50    <50
16   18         16             0     40   >=50
17   20          9             0     35    <50
18   21          8             0     40   >=50
19   22          6             1     40   >=50
20   23      

In [19]:
salary_set=set(dataset['salary'])
dataset['salary']=dataset['salary'].map({'>=50':1,'<50':0}).astype(int)

In [20]:
X=dataset.iloc[:, :-1].values
print( X)
Y= dataset.iloc[:, -1].values
print (Y)

[[10 10  0 40]
 [11  9  0 35]
 [23  6  0 40]
 [34 18  0 40]
 [45 17  0 50]
 [ 5  2  0 40]
 [ 6  2  0 35]
 [67  5  0 40]
 [32  4  1 40]
 [41  4  1 23]
 [20  4  1 20]
 [14 11  0 40]
 [13 12  0 35]
 [16 13  0 40]
 [17 14  0 40]
 [19 15  0 50]
 [18 16  0 40]
 [20  9  0 35]
 [21  8  0 40]
 [22  6  1 40]
 [23  4  1 23]
 [24 19  1 20]
 [34 17  0 40]
 [45  2  0 35]
 [36  2  0 40]
 [38  5  0 40]
 [39  4  0 50]
 [40  4  0 40]
 [41  4  0 35]
 [42 11  0 40]
 [43 12  1 40]]
[1 1 1 0 0 1 0 1 1 0 1 1 1 1 0 0 1 0 1 1 0 1 1 1 1 0 0 1 0 1 1]


In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train,Y_test = train_test_split(X,Y,test_size=.75,random_state=0)

In [25]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train = sc.fit_transform(X_train)
X_test=sc.transform(X_test)

Finding best K value

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
for i in range(1,40):
  model = KNeighborsClassifier(n_neighbors=i)
  model.fit